<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="prep2_Testng.CarLoan" tests="1" time="0.016" ignored="7" failures="1" timestamp="22 Nov 2019 10:42:54 GMT" skipped="0" hostname="DESKTOP-QJ8FI0G" errors="0">
  <testcase name="clWebLogin" time="0.016" classname="prep2_Testng.CarLoan">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at prep2_Testng.CarLoan.clWebLogin(CarLoan.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- clWebLogin -->
  <testcase name="plMobile" classname="prep2_Testng.PersonalLoan">
    <skipped/>
  </testcase> <!-- plMobile -->
  <testcase name="plWebLogin" classname="prep2_Testng.PersonalLoan">
    <skipped/>
  </testcase> <!-- plWebLogin -->
  <testcase name="Testingpersonalloan" classname="prep2_Testng.Annotations">
    <skipped/>
  </testcase> <!-- Testingpersonalloan -->
  <testcase name="Testingpersonalloan3" classname="prep2_Testng.Annotations">
    <skipped/>
  </testcase> <!-- Testingpersonalloan3 -->
  <testcase name="Testingpersonalloan2" classname="prep2_Testng.Annotations">
    <skipped/>
  </testcase> <!-- Testingpersonalloan2 -->
  <testcase name="clAPI" classname="prep2_Testng.CarLoan">
    <skipped/>
  </testcase> <!-- clAPI -->
  <testcase name="clMobile" classname="prep2_Testng.CarLoan">
    <skipped/>
  </testcase> <!-- clMobile -->
</testsuite> <!-- prep2_Testng.CarLoan -->
